*** Settings ***

Library    SeleniumLibrary
Library    BuiltIn

*** Variable ***
${SelectGenderFemale}   xpath=(//div[@class="form-check"])[1]
${SelectGenderMale}     xpath=(//div[@class="form-check"])[2]
${NameTextbox}          xpath=//input[@id="tb-name_0_0"]
${SurnameTextbox}       xpath=//input[@id="tb-surname_0_0"]
${BirthdayTextbox}      xpath=//input[@id="tb-birthdate_0_0"]
${EmailTextbox}         xpath=//input[@id="tb-email_0_0"]
${GsmTextbox}           xpath=//input[@id="contactFormPhoneNumber-g1"]
${IdCardTextbox}         xpath=//input[@id="tckn_0_0"]
${ContinueToPurchase}      xpath=//button[@id="btn-preBook"]
${PaymentMethodsField}    xpath=//div[@id="paymentMethods"]
${PayWithCard}       xpath=//div[@id="heading-CREDITCARD"]
${PayWithGarantiPay}        xpah=//div[@id="heading-GARANTIPAY"]
${PayWithCompay}          xpath=//div[@id="heading-COMPAY"]
${PayWithPaycell}         xpath=//div[@id="heading-PAYCELL"]
${CardDetailBox}      xpath=(//div[@class="payment-area payment-card"])[1]
${GarantiPayDetailBox}      xpath=(//div[@class="payment-area payment-card"])[1]
${PaycellDetailBox}      xpath=(//div[@class="payment-area payment-card"])[3]
${CardOwnerNameTextbox}       xpath=//input[@id="creditCardOwnerName"]
${CardNumberTextbox}       xpath=//input[@id="tb-creditCardNumber"]
${CardValidMonthButton}         xpath=//select[@name="creditCardValidMonth"]
${SelectValidMonth1}        xpath=//option[@value="01"]
${SelectValidMonth2}        xpath=//option[@value="02"]
${SelectValidMonth3}        xpath=//option[@value="03"]
${SelectValidMonth4}        xpath=//option[@value="04"]
${SelectValidMonth5}        xpath=//option[@value="05"]
${SelectValidMonth6}        xpath=//option[@value="06"]
${SelectValidMonth7}        xpath=//option[@value="07"]
${SelectValidMonth8}        xpath=//option[@value="08"]
${SelectValidMonth9}        xpath=//option[@value="09"]
${SelectValidMonth10}        xpath=//option[@value="10"]
${SelectValidMonth11}        xpath=//option[@value="11"]
${SelectValidMonth12}        xpath=//option[@value="12"]
${CardValidYearButton}         xpath=//select[@name="creditCardValidYear"]
${SelectValidYear22}        xpath=//option[@value="22"]
${SelectValidYear23}        xpath=//option[@value="23"]
${SelectValidYear24}        xpath=//option[@value="24"]
${SelectValidYear25}        xpath=//option[@value="25"]
${SelectValidYear26}        xpath=//option[@value="26"]
${SelectValidYear27}        xpath=//option[@value="27"]
${SelectValidYear28}        xpath=//option[@value="28"]
${SelectValidYear29}        xpath=//option[@value="29"]
${SelectValidYear30}        xpath=//option[@value="30"]
${SelectValidYear31}        xpath=//option[@value="31"]
${CvcTextbox}         xpath=//input[@name="creditCardCVC"]
${TotalAmount}        xpath=//span[@class="installment-total-amount"]
${CreateBookingButton}          xpath=//button[@id="btn-book"]
